In [33]:
import torch

scalar1 = torch.tensor([1.])
print(scalar1)

scalar2 = torch.tensor([3.])
print(scalar2)

tensor([1.])
tensor([3.])


In [34]:
add_scalar = scalar1 + scalar2
print(add_scalar)

tensor([4.])


In [35]:
sub_scalar = scalar1 - scalar2
print(sub_scalar)

# mul and div is same as expected

tensor([-2.])


In [36]:
torch.add(scalar1,scalar2)

tensor([4.])

In [37]:
vector1 = torch.tensor([1., 2., 3.])
vector2 = torch.tensor([2., 5., 1.])

print(torch.add(vector1, vector2))
add_vector = vector1 + vector2
print(add_vector)

tensor([3., 7., 4.])
tensor([3., 7., 4.])


In [38]:
if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
else:
    DEVICE = torch.device('cpu')

In [39]:
BATCH_SIZE = 64 
INPUT_SIZE = 1000
HIDDEN_SIZE = 100
OUTPUT_SIZE = 10
DEVICE

device(type='cuda')

In [51]:
x = torch.randn(BATCH_SIZE,INPUT_SIZE,device=DEVICE,dtype= torch.float, requires_grad = False)
y = torch.randn(BATCH_SIZE,OUTPUT_SIZE,device=DEVICE,dtype= torch.float, requires_grad = False)
w1 = torch.randn(INPUT_SIZE,HIDDEN_SIZE,device=DEVICE,dtype= torch.float, requires_grad = True)
w2 = torch.randn(HIDDEN_SIZE,OUTPUT_SIZE,device=DEVICE,dtype= torch.float, requires_grad = True)


In [52]:
print(x.shape)
print(y.shape)
print(w1.shape)
print(w2.shape)


torch.Size([64, 1000])
torch.Size([64, 10])
torch.Size([1000, 100])
torch.Size([100, 10])


In [53]:
y_pred = x.mm(w1).clamp(min = 0).mm(w2)
print(y_pred.shape)
loss = (y_pred - y).pow(2).sum()
print(loss.item())

torch.Size([64, 10])
27878492.0


In [54]:
learning_rate = 1e-6
for t in range(1, 501):
    y_pred = x.mm(w1).clamp(min = 0).mm(w2)
    
    loss = (y_pred - y).pow(2).sum() # Euclid distance
    
    if t % 100 == 0:
        print("Iteration: ", t, "\t", "Loss: ",loss.item())
    
    loss.backward()
    
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        
        w1.grad.zero_()
        w2.grad.zero_()

Iteration:  100 	 Loss:  929.3438110351562
Iteration:  200 	 Loss:  13.90540885925293
Iteration:  300 	 Loss:  0.42206940054893494
Iteration:  400 	 Loss:  0.01781410351395607
Iteration:  500 	 Loss:  0.0012197820469737053
